### ISSUE TITLE
Add JWT support

### ISSUE THREAD

**Issue by invisal** [invisal/god_crypto#11]
Since we aims to be one stop crypto library for Deno. It would be nice to have JWT built-in support in our library.

**Comment by LyhourChhen** [comment]
Count me in here.

**Comment by pbkh-hengborann** [comment]
I would like to contribute too. :smile:

**Comment by invisal** [comment]
We can follow the [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) so that most developer can be familiar feeling. If you have problem in implement, feel free to ask here.

**More References**
- [JSON Web Token (JWT)](https://tools.ietf.org/html/rfc7519)
- [https://www.rfc-editor.org/rfc/rfc7515.html](https://www.rfc-editor.org/rfc/rfc7515.html)

**Comment by invisal** [comment]
While I would like this library to support JWT natively, I believe our main focus now should be making the library ready for production.
