### ISSUE TITLE
Give your library a professional name.

### ISSUE THREAD

**Issue by suchislife801** [invisal/god_crypto#14]
Hello. Great library. Very useful.

Please considering changing the name to something professional that people will trust.

Also, please add support to PKCS7 for signed and encrypted email messages.

**Comment by invisal** [comment]
Thanks for finding this library useful. I am bad at naming the library. Do you have any suggestion?

I will check the PKCS7 this week. Hopefully, I can have it implemented this week.

**Comment by diguifi** [comment]
I don't mean to be rude but, I think it's really cool for the library to be named after what the creator thinks its a cool name.  
I don't mind at all to say "I use god crypto on my app" xD
