### ISSUE TITLE
Symmetric vs Asymmetric

### ISSUE THREAD

**Issue by larshp** [invisal/god_crypto#2]
Hi,
According to https://en.wikipedia.org/wiki/Advanced_Encryption_Standard, AES is symmetric

and RSA is asymmetric, https://www.ssl2buy.com/wiki/symmetric-vs-asymmetric-encryption-what-are-differences

**Comment by invisal** [comment]
Oh silly me. Got mix up. Thanks for spotting this one.

**Comment by invisal** [comment]
The README has been changed. Case closed. Thanks for reporting.
