### ISSUE TITLE
Error in example!

### ISSUE THREAD

**Issue by michailVestnik** [invisal/god_crypto#22]
const cipher = await aes.encrypt("This is AES-128-CBC. It works.");
console.log(cipher.hex());

// 41393374609eaee39fbe57c96b43a9da0d547c290501be50f983ecaac6c5fd1c
const plain = await aes.decrypt(ciper);

Decrypt cipher, no ciper

**Comment by invisal** [comment]
Thanks for reporting. There is typo in the example. I will fix it soon.
