### ISSUE TITLE
TLS alert received: https://deno.land/x/god_crypto@v1.4.8/src/utility/asn1.ts

### ISSUE THREAD

**Issue by flemux** [invisal/god_crypto#23]
Been getting this error just today, linked to the latest version of god_crypto?

`
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/common.ts
Download https://deno.land/x/djwt@v2.0/signature.ts
Download https://deno.land/x/djwt@v2.0/algorithm.ts
Download https://deno.land/x/djwt@v2.0/deps.ts
Download https://deno.land/x/god_crypto@v1.4.6/rsa.ts
Download https://deno.land/std@0.80.0/hash/sha512.ts
Download https://deno.land/std@0.80.0/hash/sha256.ts
Download https://deno.land/std@0.80.0/encoding/base64url.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/rsa/mod.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/mod.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/rsa/common.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/binary.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/rsa/rsa_js.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/rsa/rsa_wc.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/rsa/rsa_key.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/rsa/import_key.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/rsa_js.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/import_key.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/rsa_key.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/rsa_wc.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/binary.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/hash.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/rsa/rsa_internal.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/utility/encode.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/rsa/export_key.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/hash.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/rsassa_pss.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/rsa_internal.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/helper.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/utility/encode.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/primitives.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/basic_encoding_rule.ts
Download https://denopkg.com/chiefbiiko/sha256@v1.0.2/mod.ts
Download https://denopkg.com/chiefbiiko/sha1@v1.0.3/mod.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/rsa/primitives.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/helper.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/rsa/eme_oaep.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/math.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/rsa/basic_encoding_rule.ts
Download https://deno.land/x/god_crypto@v1.4.6/src/utility/asn1.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/export_key.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/emsa_pss.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/math.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/rsa/eme_oaep.ts
Download https://denopkg.com/chiefbiiko/sha512/mod.ts
Download https://deno.land/x/god_crypto@v1.4.8/src/utility/asn1.ts
TLS alert received: Message {
    typ: Alert,
    version: TLSv1_2,
    payload: Alert(
        AlertMessagePayload {
            level: Fatal,
            description: InternalError,
        },
    ),
}
error: error sending request for url (https://denopkg.com/chiefbiiko/sha512/mod.ts): error trying to connect: received fatal alert: InternalError
    at https://deno.land/x/god_crypto@v1.4.8/src/hash.ts:3:0

`

**Comment by invisal** [comment]
It is not from our side. I believe this is from `https://deno.land/x/sha512@v1.0.3` package which we rely on. Are you still having the problem?

**Comment by fredlemieux** [comment]
I'm back on the 4th of Jan, so I'll check then and see if I can dig into this some more.  Have a happy new year!

**Comment by flemux** [comment]
Good news! This is no longer a problem now!  Fixed, but not sure how.  I'll close this.
