### ISSUE TITLE
RSA.importKey fails for Certificate

### ISSUE THREAD

**Issue by jpsSO** [invisal/god_crypto#24]
When I try to import a certificate, 
e..g.
const certificate=`-----BEGIN CERTIFICATE-----
MIIC6jCCAdKgAwIBAgIGAXaVe94SMA0GCSqGSIb3DQEBCwUAMDYxNDAyBgNVBAMM
K1g5ckRRSWdRdmdidkFnNEJvb18wbklUU054MDYxTXNHSGQ4dlV1QkNMUncwHhcN
MjAxMjI0MTYwMTMxWhcNMjExMDIwMTYwMTMxWjA2MTQwMgYDVQQDDCtYOXJEUUln
UXZnYnZBZzRCb29fMG5JVFNOeDA2MU1zR0hkOHZVdUJDTFJ3MIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEApGleHRGOs1scVRpv6fPcbnO4ymFgTRYtahiR
D5CVSAfZBr2CuQXXMpMzAEM58qQJ/TzxsLIFHg/VO54DQlhbCrTPBTEGYb5S5/Jw
iDLrWdGNY5Dixx73VfOPMy7R0OKOGE5TsETPaWHXaY8PuCSUGQpWlt/pbU1BJvOZ
5Ls9AVG8r72ZHwnWmQBbgwiaRbinvN9Dt1IuV3wbqk1Xg5hdYaaPBi4JX9IzRPG4
6GrqbX4HlxByLYYO6fMD9jmlyFtfO9119I60bsK+muPWzDk3FeevRpKHrkZx3HZi
m/yTkYmgYj4X9ZCQtu0MlBIB/rZGG75RppFQn9pZucF/0IhupQIDAQABMA0GCSqG
SIb3DQEBCwUAA4IBAQCO/FPK6OzmreIJ6ilgYeHJGkTTTDkH6tKAfkzY43znlYmv
s+RBOkxHHejdSeIAicBD49hLcwwWDJDJdyg/CleRBYX5jS1IPR8jA+qgFrOeWtZk
jggxSac8r9sipyxq1sxLBVFYPhRAN5dBE6dp5WMqUnv5QE0bvJ0MzfBUA3DlktSH
ZD9BrpdCeytf34m3QWbsgKHUSbKZGeTch/Skyuc+bXspjtf9LQFWsSJ/9nnVfG0M
L8f/6e1mTV8Jzbh4lN5tqWTn3VwwBw9IxJL6+LodvAIimX680hwhizOZsI52vWvW
ElJu6L9bDNYoFN62AI2v8I4JpH3VtSA8UoudtVku
-----END CERTIFICATE-----`

const Key = RSA.importKey(certificate)

it fails with 

error: Uncaught TypeError: Cannot read property '0' of undefined
var length = get_key_size(parseKey[0][5][1][0][0]);

Is it a mistake on my side or a bug? 
I tried with the certificate in your testcase (https://github.com/invisal/god_crypto/blob/master/tests/rsa/rsa.import_key.test.ts) and it works fine.

**Comment by invisal** [comment]
Which program are you use for generating this certificate?

**Comment by jpsSO** [comment]
I created it with https://mkjwk.org/ but with certificates from google (https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com) it's the same problem.

**Comment by invisal** [comment]
I know what is the problem. I will work on the update to support the certification. As I decode your certificate comparing to the certificate in the in the test case, there is a difference. The certificate that I used in my test case is version 3. Your current certificate is version 2. (https://tools.ietf.org/html/rfc5280#section-4.1.2.1)

I will read more detail on the certificate format and work on the solution to support all version. Thanks for reporting.

**Comment by jpsSO** [comment]
Thanks for the quick response. Good to know that you already found the issue.

**Comment by timonson** [comment]
@invisal is the following issue connected to this one here or do you have an idea what might cause it? Thank you!
https://github.com/timonson/djwt/issues/47

**Comment by samuelgozi** [comment]
Im also having this issue when trying to parse the keys google uses in firebase:
https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-p97r6%40void-eu.iam.gserviceaccount.com

**Comment by jpsSO** [comment]
This can be solved now by using crypto.suble in Deno as demonstrated hee https://stackoverflow.com/questions/65430344/verify-firebase-id-tokens-jwt-using-deno-djwt
