### ISSUE TITLE
How to get BlockCipher from hex?

### ISSUE THREAD

**Issue by kryptish** [invisal/god_crypto#5]
Probably a stupid question, but need to ask anyways, the example calls `.hex()` on the encrypted cipher, which returns a string. Say I store this encrypted text, how would I pass this text to `aes.decrypt()` again so it can be decrypted? As far as I can understand from the code, `decrypt()` expects a BlockCiper object, but how do I get one from a hex string?

thanks and sorry again for the question =)...

EDIT: I dug around crypto-js a bit and found how they convert a hex string to bytes:

```
	// Convert a hex string to a byte array
	function hex2bytes(hex) {
		for (var bytes = [], c = 0; c < hex.length; c += 2)
		bytes.push(parseInt(hex.substr(c, 2), 16));
		return bytes;
	}
```

but wouldn't it be useful if god_crypto would do that by itself, e.g. some kind of flag or something for `decrypt()` when the input is a string, e.g. something like `.decrypt(<string>, '<hex|base64>')`

**Comment by invisal** [comment]
`.decrypt` does not expect BlockCiper, it expects `string` or `Uint8Array`. `encrypt` and `decrypt` all returns `RawBinary` which basically extends from `Uint8Array` and add a few convenience method like `.hex()` or `.base64()`.

Currently, you can store the `Uint8Array`, but if it is more convenience to hex or base64 somewhere and later on use it to decrypt back. I can add it quickly. It shouldn't be hard.

One more thing, we will release new version. Everything will be promise-based to be more consistence with the WebCrypto. We also use WebCrypto now if it is available and only fallback to our Javascript implement if WebCrypto is not available.

**Comment by kryptish** [comment]
Thanks for the clearification! I tried to pass the hex string to `.decrypt()` but that didn't work (obviously), how would you store the encrypted value as Uint8Array in a JSON file? I'm using deno, which afaik does not implement WebCrypto completely, right? there is a window.crypto object but it doesn't seem to have all the methods available in the browser...

**Comment by invisal** [comment]
Deno can be compiled and work inside the browser. If it is inside the browser, we will use WebCrypto if available. If you run from deno command line, it will use Javascript implementation. You can store Uint8Array in a JSON file as array of number, but I think storing base64 is better option. I will implement a few helper function to convert hex/base64 back into Uint8Array. Probably will be done pretty soon.

**Comment by invisal** [comment]
We have added the utility for encoding. You can use as following

```
const aes = new AES(key, { mode: "cbc", iv: "some_random_iv...." });
await aes.decrypt(encode.hex("some_hex_value"));
```
